name: CI Validation

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Bundle install
        run: |
          gem install bundle
          bundle install

      - name: RuboCop validation
      with:
        action_config_path: ".github/config/rubocop_action.yml"

      - name: RSpec tests
        run: bundle exec rspec
